#!/usr/bin/env python3
"""
Prepare test dataset for inference experiments.

Uses real test features generated by scripts/train_models.py (Adult Income or
Breast Cancer). Run train_models.py first to produce adult_test_inputs.npy and
cancer_test_inputs.npy under data/.

Writes data/test_inputs.npy (path configurable). Used for reproducible artifact inputs.
"""
from pathlib import Path
import argparse
import numpy as np


def get_default_data_dir() -> Path:
    return Path(__file__).resolve().parent.parent / "data"


def copy_real_dataset(dataset: str, size: int, out_dir: Path) -> Path:
    """
    Copy (optionally subsample) real test features prepared by train_models.py
    into a common test_inputs.npy file.
    """
    base_dir = get_default_data_dir()
    if dataset == "adult":
        src = base_dir / "adult_test_inputs.npy"
    elif dataset == "cancer":
        src = base_dir / "cancer_test_inputs.npy"
    else:
        raise ValueError(f"Unknown dataset: {dataset}")

    if not src.exists():
        raise FileNotFoundError(
            f"{src} does not exist. Run scripts/train_models.py first to generate real test features."
        )

    X = np.load(src)
    if size > 0 and size < X.shape[0]:
        X = X[:size]
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "test_inputs.npy"
    np.save(out_path, X.astype(np.float32))
    return out_path


def main():
    parser = argparse.ArgumentParser(description="Prepare test data for inference experiments.")
    parser.add_argument("--data-dir", type=Path, default=None, help="Output directory (default: project data/)")
    parser.add_argument("--size", type=int, default=100, help="Number of samples (e.g. 100, 1000, 10000)")
    parser.add_argument(
        "--dataset",
        choices=["adult", "cancer"],
        default="adult",
        help="Which dataset to use. Run scripts/train_models.py first to generate test features.",
    )
    args = parser.parse_args()
    data_dir = args.data_dir or get_default_data_dir()
    path = copy_real_dataset(args.dataset, args.size, data_dir)
    print(f"Saved test data from '{args.dataset}' to {path} (size <= {args.size})")


if __name__ == "__main__":
    main()
